[package]
name = 'didcomm-module'
version = '0.0.1'
edition = '2018'
readme = 'README.md'

[lib]
crate-type = ['cdylib', 'rlib']

[dependencies]
didcomm = { version = "0.4.1", default-features = false }
serde_json = '1.0'
uuid = { version = "0.8", features = ["v4", "wasm-bindgen"] }
serde = "1.0.219"
chrono = { version = "0.4.40" }

[profile.release]
opt-level = 's'
lto = true