[package]
name = "didcomm-module-wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ['cdylib', 'rlib']

[dependencies]
wasm-bindgen = { version = "0.2.100", features = ["serde-serialize"] }
tsify = "0.5.5"
serde = { version = "1.0", features = ["derive"] }
didcomm-module = {path = "../"}
serde_json = '1.0'
url = { version = "2.5.4", default-features = false }
didcomm = { version = "0.4.1", default-features = false }
wasm-bindgen-futures = "0.4.50"
serde-wasm-bindgen = "0.6.5"
console_error_panic_hook = "0.1.7"
